#!/usr/bin/env sh

echo `date`>$HOME/changelog/changelog.log
# Log everything
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>$HOME/changelog/changelog.log 2>&1
set -x

_change_dir="$HOME/changelog"
_distrib=$(cat /etc/os-release | awk -F= '/^NAME/ {print $2}')

# CREDENTIALS
_user=$(cat $_change_dir/credential | awk '/user/ {print $2}')
_pass=$(cat $_change_dir/credential | awk '/pass/ {print $2}')
_url=$(cat $_change_dir/credential | awk '/url/ {print $2}')

### FETCH CHANGELOG.TXT
curl -k -q --no-progress-meter -o $_change_dir/ChangeLog.1.txt http://ftp.slackware.com/pub/slackware/slackware64-current/ChangeLog.txt
### MD5SUM
md5 $_change_dir/ChangeLog.1.txt > $_change_dir/ChangeLog.1.md5
_md5_1=$(cat $_change_dir/ChangeLog.1.md5 | cut -d= -f2 | sed 's/ //')

### IN CASE OF EXECUTION IS NOT UNDER A SLACK BOX
if [ $_distrib = "Slackware" ]; then
  md5 /var/lib/slackpkg/ChangeLog.txt > $_change_dir/ChangeLog.2.md5
  _md5_2=$(cat $_change_dir/ChangeLog.2.md5 | cut -d= -f2 | sed 's/ //')
else
  if [ -f $_change_dir/ChangeLog.2.md5 ]; then
    _md5_2=$(cat $_change_dir/ChangeLog.2.md5 | cut -d= -f2 | sed 's/ //')
  else
    touch $_change_dir/ChangeLog.2.txt
    md5 $_change_dir/ChangeLog.2.txt > $_change_dir/ChangeLog.2.md5
  fi
fi

### COUNT
_number_total=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e txz  -e img -e "kernel/*" \
  | grep -e Upgraded -e Added -e Rebuilt -e Removed \
  | wc -l | sed 's/ *//g'
  )
_number_total_test_1=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e txz  | grep -e testing \
  | wc -l | sed 's/ *//g'
  )
_number_upgraded_1=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e txz -e img -e "kernel/*" | grep -e Upgraded \
  | grep -v testing | wc -l | sed 's/ *//g'
  )
_number_added_1=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e txz -e img -e "kernel/*" | grep -e Added \
  | grep -v testing | wc -l | sed 's/ *//g'
  )
_number_rebuilt_1=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e txz -e img -e "kernel/*" | grep -e Rebuilt \
  | grep -v testing | wc -l | sed 's/ *//g'
  )
_number_removed_1=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e txz -e img -e "kernel/*" | grep -e Removed \
  | grep -v testing | wc -l | sed 's/ *//g'
  )
_number_security_1=$(diff $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt \
  | grep -e Security | wc -l | sed 's/ *//g'
  )
### ECHO NUMBERS, ELSE ECHO "0"
_number_upgraded=${_number_upgraded_1:-0}
_number_added=${_number_added_1:-0}
_number_rebuilt=${_number_rebuilt_1:-0}
_number_removed=${_number_removed_1:-0}
_number_security=${_number_security_1:-0}
_number_total_test=${_number_total_test_1:-0}

### MAIN
if [ ${_md5_1} = ${_md5_2} ]; then
  exit 0
else
  /usr/local/bin/curl ${_url}\?user\=${_user}\&pass\=${_pass}\&msg\="Slackware: $_number_total updates availables%0D\
----------%0D\
$_number_upgraded Upgraded%0D\
$_number_added Added%0D\
$_number_rebuilt Rebuilt%0D\
$_number_removed Removed%0D\
Include: $_number_security Security fix%0D\
Include: $_number_total_test Testing"
  # Rotate the txt files
  cp $_change_dir/ChangeLog.2.txt $_change_dir/ChangeLog.2.txt.bak  # keep a backup, for rollback/tests
  cp $_change_dir/ChangeLog.1.txt $_change_dir/ChangeLog.2.txt
  cp $_change_dir/ChangeLog.2.md5 $_change_dir/ChangeLog.2.md5.bak  # keep a backup, for rollback/tests
  cp $_change_dir/ChangeLog.1.md5 $_change_dir/ChangeLog.2.md5
fi
